"""Changed column name

Revision ID: 1fc8d74c6a09
Revises: c7c388de739c
Create Date: 2024-01-25 15:44:04.925804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc8d74c6a09'
down_revision = 'c7c388de739c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locationid', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('shared_georeference_geopick_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['locationid'])
        batch_op.drop_column('geopick_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geopick_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('shared_georeference_geopick_id_key', ['geopick_id'])
        batch_op.drop_column('locationid')

    # ### end Alembic commands ###
