"""Changed field name

Revision ID: 7f38ad795be3
Revises: b999560f1f65
Create Date: 2024-01-18 15:59:11.765156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f38ad795be3'
down_revision = 'b999560f1f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geopick_id', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('shared_georeferences_identifier_key', type_='unique')
        batch_op.create_unique_constraint(None, ['geopick_id'])
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('shared_georeferences_identifier_key', ['identifier'])
        batch_op.drop_column('geopick_id')

    # ### end Alembic commands ###
