"""empty message

Revision ID: 939bb3dfe5d6
Revises: 1fc8d74c6a09
Create Date: 2024-01-26 12:01:17.657572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939bb3dfe5d6'
down_revision = '1fc8d74c6a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
