"""Dropped column

Revision ID: c7c388de739c
Revises: d93d55f8c3aa
Create Date: 2024-01-18 17:07:50.846177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c388de739c'
down_revision = 'd93d55f8c3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.drop_constraint('shared_georeference_shortcode_key', type_='unique')
        batch_op.drop_column('shortcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_georeference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortcode', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('shared_georeference_shortcode_key', ['shortcode'])

    # ### end Alembic commands ###
