library(geojsonsf)
library(httr)
library(dplyr)
library(plumber)
library(sf)
library(terra)
library(jsonlite)
library(leaflet)
library(geojsonR)
library(lwgeom)
library(mapview)
library(tictoc)
# wget "http://nominatim.openstreetmap.org/search?q=catalunya&polygon_geojson=1&format=json" -O cat.json
unlink("tmp/catalunya.*")
unlink("tmp/catalunya_simplified.*")
sf <- st_read("tmp/cat.json") %>% filter(grepl("MULTIPOLYGON", st_geometry_type(sf)))
st_write(sf, dsn="tmp/catalunya.shp")

site.geojson <- sf_geojson(sf)
site.sf <- geojson_sf(site.geojson)
site.sf <- site.sf %>% summarise(geometry = st_combine(geometry))
print(npts(site.sf))
site.sf <- st_simplify(site.sf, preserveTopology = TRUE, dTolerance = 7.9)
print(npts(site.sf))
st_write(site.sf, dsn="tmp/catalunya_simplified.shp")
site.tr <- st_transform(site.sf, 3857)
tic()
mbc.tr <- st_minimum_bounding_circle(site.tr, nQuadSegs = 30)
toc()
plot(mbc.tr)
plot(site.tr, add=T)


site.geojson <- sf_geojson(sf)
site.sf <- geojson_sf(site.geojson)
site.sf <- site.sf %>% summarise(geometry = st_combine(geometry))
print(npts(site.sf))
site.tr <- st_transform(site.sf, 3857)
site.tr <- st_simplify(site.tr, preserveTopology = TRUE, dTolerance = 25)
print(npts(site.tr))
tic()
mbc.tr <- st_minimum_bounding_circle(site.tr, nQuadSegs = 30)
toc()
plot(mbc.tr)
plot(site.tr, add=T)


plotMBC <- function(name, tolerance = 25){
  for(ext in c("shp", "shx", "dbf", "prj")){
    unlink(paste0("tmp/", name, ".", ext))
    unlink(paste0("tmp/", name, "_simplified.", ext))
  }
  sf <- st_read(paste0("tmp/", name, ".json"))
  st_write(sf, paste0("tmp/", name, ".shp"))
  site.geojson <- sf_geojson(sf)
  site.sf <- geojson_sf(site.geojson)
  site.sf <- site.sf %>% summarise(geometry = st_combine(geometry))
  print(npts(site.sf))
  site.tr <- st_transform(site.sf, 3857)
  if(npts(site.tr) > 10000){
    site.tr <- st_simplify(site.tr, preserveTopology = TRUE, dTolerance = tolerance)
  }
  
  print(npts(site.tr))
  tic()
  mbc.tr <- st_minimum_bounding_circle(site.tr, nQuadSegs = 30)
  toc()
  plot(mbc.tr)
  plot(site.tr, add=T)
}
plotMBC("ind", 15)
plotMBC("ind", 25)
plotMBC("fin", 0)
plotMBC("nor", 0)
plotMBC("aus", 0)
plotMBC("uk", 100)
plotMBC("and", 0)
plotMBC("arg", 200)
plotMBC("bra", 500)


sf <- st_read(paste0("tmp/kk.json"))
plot(site.tr)
plot(sf)
